version: "3.5"

networks: 
  app-network:
    driver: bridge

services:
  mysql:
    container_name: santins_mysql
    image: mysql
    ports: 
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'santins'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks: 
      - app-network
  phpmyadmin:
    container_name: santins_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_PASSWORD='root'
      - MYSQL_ROOT_PASSWORD='root'
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network
  back:
    container_name: santins_back
    build: ./back
    ports: 
      - "8000:8000"
    working_dir: /var/www/
    volumes:
      - ./back/:/var/www
    networks: 
      - app-network
    depends_on:
      - mysql
  front:
    container_name: santins_front
    build: ./front
    ports: 
      - "3000:3000"
    volumes:
      - ./front/:/var/www
    networks: 
      - app-network
    depends_on:
      - back
  